### ISSUE TITLE
Trying to sign in causes an Error Responce 400

### ISSUE THREAD

**Issue by exsersewo** [RogueException/Discord.OAuth2#4]
I go to login with discord and it presents "Unknown Error", trying to find out why in the developer console returns an error 400 BAD REQUEST.

**Comment by RogueException** [comment]
I'm not sure how this lib would cause an error 400. You could try the Auth 2.0 version I just pushed.

**Comment by exsersewo** [comment]
Hey, so I just tried the 2.0 version and it's returning the error code 50040 now, I've double checked the response uri on the application and it's the exact same as the url I'm trying it with.

**Comment by exsersewo** [comment]
forgot to add `signin-discord` to the callback url

**Comment by DoubleCouponDay** [comment]
>callback url
its added for you by `discordoptions.cs`
