### ISSUE TITLE
Allow Asp.Net Core 2.0 Authentication

### ISSUE THREAD

**Issue by MildanWorld** [RogueException/Discord.OAuth2#5]
So in Asp.Net Core 1.x the authentication middleware was under the IApplicationBuilder in the Configure method of Startup.cs, like you currently write in your readme.

```csharp
app.UseDiscordAuthentication(new DiscordOptions
{
    AppId = Configuration["Discord:AppId"],
    AppSecret = Configuration["Discord:AppSecret"],
    Scope = { "identify", "guilds" }
});
```

However in Asp.Net Core 2.0 they changed this so that it would be under the IServiceCollection in the ConfigureServices method of Startup.cs. If you currently try to use the above in an Asp.Net Core 2.0 project, you are met with an error on startup

```
TypeLoadException: Could not load type 'Microsoft.AspNetCore.Builder.OAuthOptions' from assembly 'Microsoft.AspNetCore.Authentication.OAuth, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
```

Steps to replicate:

1. Make a new Asp.Net Core 2.0 project with individual user accounts authentication
2. Add the Discord.OAuth2 package and try to use it like the above

Proposal:

Update the project to reflect the Asp.Net Core 2.0 changes the authentication, and making a method like

```chsarp
services.AddAuthentication().AddDiscord(discordOptions =>
{
    discordOptions.AppId = Configuration["Discord:AppId"];
    discordOptions.AppSecret = Configuration["Discord:AppSecret"];
});
```

The main problem as far as I can tell, is that the Microsoft.AspNetCore.Builder.OAuthOptions class is no longer available, which means the DiscordOptions will fail.

**Comment by MildanWorld** [comment]
[https://github.com/aspnet/Security/issues/1310](https://github.com/aspnet/Security/issues/1310) found more info on the change.
I've tried to fork the project and am trying to tinker with it to see if I can't get it running but no luck so far.

**Comment by MildanWorld** [comment]
I have tried to update the project and it actually seems to work for now.. This is the first time I've ever done anything like this so it may be full of holes and whatnot, but the project can be seen here.

https://github.com/MildanWorld/Discord.OAuth2

As far as I can tell it seems to work with ASP.NET Core 2.0 Authentication now.

**Comment by RogueException** [comment]
Ah right, completely forgot to update this project when 2.0 came out.

Should be fixed in https://github.com/RogueException/Discord.OAuth2/commit/bb63e6a4d63c9db62f2d39cc1400b48bed064d52

**Comment by MildanWorld** [comment]
Any chance to add a method like [here](https://github.com/MildanWorld/Discord.OAuth2/blob/master/src/Discord.OAuth2/DiscordOptions.cs#L28) in the DiscordOptions, so adding multiple scopes won't be as annoying?

I'll try to pull the project down and play with it though, thanks 👍

**Comment by yaakov-h** [comment]
@RogueException Any chance you could publish the 2.0-compatible version to NuGet?

**Comment by ThePieMonster** [comment]
Still seeing version 1.1.0 as the latest version on Nuget.

**Comment by simworzalla** [comment]
@RogueException Any plans to push an update to nuget?

**Comment by richard-ob** [comment]
@simworzalla they've pushed it to NuGet now! 👍

**Comment by RogueException** [comment]
Sorry everyone, haven't had much time to work on my personal projects for the past year :ablobsweats:
2.0.0 is on NuGet now.
